# Generated by Django 6.0.1 on 2026-06-15 23:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_assets",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "safe_to_spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_savings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_checking",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_investment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_cash",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_ewallet",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_monthly_spending",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_remaining_expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_leaks",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("uid", models.CharField(db_index=True, max_length=200)),
            ],
            options={
                "verbose_name_plural": "Financial Snapshot",
            },
        ),

        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list, null=True)),
                ("uid", models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="AppProfile",
            fields=[
                (
                    "user_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "spend_accounts",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("base_currency", models.CharField(default="USD", max_length=3)),
                ("timezone", models.CharField(default="America/New_York")),
                ("start_of_week", models.IntegerField(default=1)),

                (
                    "username",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("uid", models.CharField(db_index=True, max_length=200)),
            ],
            options={
                "verbose_name_plural": ("Categories",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "uid"), name="unique_category_per_user"
                    )
                ],
            },
        ),

        migrations.CreateModel(
            name="PaymentSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=50)),
                (
                    "acc_type",
                    models.CharField(
                        choices=[
                            ("SAVINGS", "Savings"),
                            ("CHECKING", "Checking"),
                            ("CASH", "Cash"),
                            ("INVESTMENT", "Investment"),
                            ("EWALLET", "Mobile Wallet"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=10,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("uid", models.CharField(db_index=True, max_length=200)),
            ],
            options={
                "verbose_name_plural": "Payment Sources",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "uid"), name="unique_source_per_user"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_on", models.DateField()),
                ("category", models.CharField(blank=True, max_length=200, null=True)),
                ("source", models.CharField(max_length=50)),
                ("currency", models.CharField(max_length=3)),
                ("tags", models.JSONField(blank=True, default=list, null=True)),
                (
                    "tx_id",
                    models.CharField(db_index=True, editable=False, max_length=20),
                ),
                ("bill", models.CharField(blank=True, max_length=200, null=True)),
                ("uid", models.CharField(db_index=True, max_length=200)),
                (
                    "tx_type",
                    models.CharField(
                        choices=[
                            ("EXPENSE", "Expense"),
                            ("INCOME", "Income"),
                            ("XFER_IN", "Transfer In"),
                            ("XFER_OUT", "Transfer Out"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tx_id", "uid"), name="unique_transaction_per_user"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UpcomingExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("paid_flag", models.BooleanField(default=False)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("uid", models.CharField(db_index=True, max_length=200)),
                ("is_recurring", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["due_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "uid"), name="unique_upcoming_expense_per_user"
                    )
                ],
            },
        ),
    ]
