# Generated by Django 6.0.1 on 2026-02-15 20:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppProfile",
            fields=[
                (
                    "user_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("last_login", models.DateField(blank=True, null=True)),
                (
                    "username",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "cat_type",
                    models.CharField(
                        choices=[
                            ("BILL", "Recurring Bill"),
                            ("DAILY", "Daily Expense"),
                            ("INCOME", "Income Source"),
                            ("XFER", "Transfer"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "uid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.appprofile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(default="USD", max_length=3, unique=True)),
                ("name", models.CharField(default="USD", max_length=50)),
                ("symbol", models.CharField(default="$", max_length=5)),
                (
                    "uid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.appprofile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Currencies",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="appprofile",
            name="base_currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="finance.currency",
            ),
        ),
        migrations.CreateModel(
            name="FinancialSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_assets", models.DecimalField(decimal_places=2, max_digits=15)),
                ("safe_to_spend", models.DecimalField(decimal_places=2, max_digits=15)),
                ("total_savings", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "total_checking",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "total_investment",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("total_cash", models.DecimalField(decimal_places=2, max_digits=15)),
                ("total_ewallet", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "total_monthly_spending",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "total_remaining_expenses",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("total_leaks", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "uid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.appprofile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Financial Snapshot",
            },
        ),
        migrations.CreateModel(
            name="PaymentSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=50, unique=True)),
                (
                    "acc_type",
                    models.CharField(
                        choices=[
                            ("SAVINGS", "Savings"),
                            ("CHECKING", "Checking"),
                            ("CASH", "Cash"),
                            ("INVESTMENT", "Investment"),
                            ("EWALLET", "Mobile Wallet"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "uid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.appprofile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Payment Sources",
            },
        ),
        migrations.CreateModel(
            name="CurrentAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.currency",
                    ),
                ),
                (
                    "uid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.appprofile",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.paymentsource",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Current Assets",
            },
        ),
        migrations.AddField(
            model_name="appprofile",
            name="spend_accounts",
            field=models.ManyToManyField(blank=True, to="finance.paymentsource"),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "uid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.appprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("date", models.DateField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "entry_id",
                    models.AutoField(db_index=True, primary_key=True, serialize=False),
                ),
                ("tx_id", models.CharField(editable=False, max_length=20, unique=True)),
                (
                    "tx_type",
                    models.CharField(
                        choices=[
                            ("EXPENSE", "Expense"),
                            ("INCOME", "Income"),
                            ("XFER", "Transfer"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.category",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.currency",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.paymentsource",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="finance.tag")),
                (
                    "uid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.appprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="UpcomingExpense",
            fields=[
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("paid_flag", models.BooleanField(default=False)),
                ("expense_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.currency",
                    ),
                ),
                (
                    "uid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.appprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date"],
            },
        ),
    ]
