# Generated by Django 6.0.1 on 2026-02-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialsnapshot",
            name="safe_to_spend",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="financialsnapshot",
            name="total_assets",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="financialsnapshot",
            name="total_cash",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="financialsnapshot",
            name="total_checking",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="financialsnapshot",
            name="total_ewallet",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="financialsnapshot",
            name="total_investment",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="financialsnapshot",
            name="total_leaks",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="financialsnapshot",
            name="total_monthly_spending",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="financialsnapshot",
            name="total_remaining_expenses",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="financialsnapshot",
            name="total_savings",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
