# Generated by Django 6.0.1 on 2026-03-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_remove_tag_unique_uuid_per_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="created_on",
            field=models.DateField(),
        ),
    ]
