# Generated by Django 6.0.1 on 2026-02-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_alter_financialsnapshot_safe_to_spend_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="tx_type",
            field=models.CharField(
                choices=[
                    ("EXPENSE", "Expense"),
                    ("INCOME", "Income"),
                    ("XFER_IN", "Transfer In"),
                    ("XFER_OUT", "Transfer Out"),
                ],
                max_length=10,
            ),
        ),
    ]
