# Generated by Django 6.0.1 on 2026-02-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_alter_transaction_amount_alter_transaction_tx_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currentasset",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
