# Generated by Django 6.0.1 on 2026-02-19 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_alter_currentasset_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="currency",
            name="uid",
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="currency",
            name="code",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AlterField(
            model_name="currentasset",
            name="source",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="finance.paymentsource"
            ),
        ),
        migrations.AlterField(
            model_name="financialsnapshot",
            name="uid",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="finance.appprofile"
            ),
        ),
        migrations.AlterField(
            model_name="paymentsource",
            name="source",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="tx_id",
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name="upcomingexpense",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("name", "uid"), name="unique_category_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="currency",
            constraint=models.UniqueConstraint(
                fields=("code", "name", "symbol"), name="unique_currency_per_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentsource",
            constraint=models.UniqueConstraint(
                fields=("source", "uid"), name="unique_source_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("name", "uid"), name="unique_tag_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                fields=("tx_id", "uid"), name="unique_transaction_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="upcomingexpense",
            constraint=models.UniqueConstraint(
                fields=("name", "uid"), name="unique_upcoming_expense_per_user"
            ),
        ),
    ]
