# Generated by Django 6.0.1 on 2026-05-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_auth_user_email_ci_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=200)),
                ("key_hash", models.CharField(db_index=True, max_length=64)),
                ("method", models.CharField(max_length=8)),
                ("path", models.CharField(max_length=512)),
                ("status_code", models.PositiveSmallIntegerField()),
                ("response_body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="finance_ide_created_69e24f_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("uid", "key_hash"), name="idempotency_uid_key_hash_uniq"
                    )
                ],
            },
        ),
    ]
