# Generated by Django 6.0.1 on 2026-02-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_remove_currency_uid_alter_category_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="symbol",
            field=models.CharField(blank=True, default="$", max_length=5, null=True),
        ),
    ]
