# Generated by Django 6.0.1 on 2026-02-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_alter_currency_symbol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upcomingexpense",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="ACTIVE",
                max_length=10,
            ),
        ),
    ]
