# Generated by Django 6.0.1 on 2026-05-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_idempotency_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="appprofile",
            name="completed_tours",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
