# Generated by Django 6.0.1 on 2026-06-15 23:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_appprofile_completed_tours"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[("BUG", "Bug"), ("FEATURE", "Feature Request")],
                        max_length=10,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("nature", models.CharField(max_length=255)),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "diagnostic_log_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("emailed", models.BooleanField(default=False)),
            ],
        ),
    ]
