# Generated by Django 6.0.1 on 2026-02-20 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_alter_upcomingexpense_status"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="category",
            name="unique_category_per_user",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="category",
        ),
        migrations.RemoveField(
            model_name="upcomingexpense",
            name="status",
        ),
        migrations.AddField(
            model_name="transaction",
            name="bill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.upcomingexpense",
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
