# Generated by Django 6.0.1 on 2026-06-26 03:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_merge_20260626"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyUsageSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("dau_count", models.PositiveIntegerField(default=0)),
                ("mau_count", models.PositiveIntegerField(default=0)),
                ("active_accounts", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="OperatorAlertState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alert_key", models.CharField(max_length=64, unique=True)),
                ("last_sent_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="InviteChainEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("inviter_uuid", models.UUIDField(db_index=True)),
                ("invitee_uuid", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="finance_inv_created_392458_idx"
                    )
                ],
            },
        ),
    ]
