# Generated by Django 6.0.1 on 2026-06-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0010_usage_monitoring_f014"),
    ]

    operations = [
        migrations.AddField(
            model_name="appprofile",
            name="tos_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appprofile",
            name="tos_version",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
