# Generated by Django 6.0.1 on 2026-06-28 03:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0014_balance_snapshot_f001"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportShareToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked", models.BooleanField(default=False)),
                (
                    "uid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_tokens",
                        to="finance.appprofile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["token"], name="finance_exp_token_2863ab_idx")
                ],
            },
        ),
    ]
