# Generated by Django 6.0.6 on 2026-07-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0020_auto_deduct_and_marker"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=200)),
                (
                    "device_class",
                    models.CharField(
                        choices=[("mobile", "Mobile"), ("desktop", "Desktop")],
                        max_length=10,
                    ),
                ),
                ("layout", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("uid", "device_class"),
                        name="dashboard_layout_uid_device_uniq",
                    )
                ],
            },
        ),
    ]
