"""
This module defines all models for the finance manager application.

Attributes:
    AppProfile: Model for user profiles.
    Currency: Global model for currencies.
    Tag: Model for tags.
    PaymentSource: Model for payment sources.
    UpcomingExpense: Model for upcoming expenses.
    Transaction: Model for transactions.
    CurrentAsset: Model for current assets.
    FinancialSnapshot: Model for financial snapshots.
"""
from django.db import models
from django.utils import timezone
from django.conf import settings
from finance.management.managers import *
import uuid



# TODO: Fix docstrings

# TODO: Fix UUID decoupling
    # Add on_delete signal to replace the decoupling
    # Cascade these changes for each model
        # Views>Serializers>Validators>Services>Updaters>Calculators

# TODO: Finish optimization refactor in Updaters:
    # Reducing database hits
    # Making sure kwargs passed are useful/reduce database hits meaningfully

# TODO: Finish all other foreignkey decoupling
    # App Profile spend accounts
    # Current Assets rolled into PaymentSource
    # Transactions
        # Source
        # Tags
        # Bill
    
# TODO: Remove "unknown" source from auto creation in Payment Source
    # Removal of direct links removes orphaned transactions
    # This may still be useful actually, since not having the source anymore makes it easier to find


class AppProfile(models.Model):
    """
    Model for user profiles. Automatically generated by Django when a user is created via api_tools/signals.py.

    Attributes:
        objects (AppProfileManager): Manager for the AppProfile model.
        username (OneToOneField): One-to-one relationship with the user model.
        user_id (UUIDField): Unique identifier for the user.
        spend_accounts (ManyToManyField): Many-to-many relationship with the PaymentSource model.
        base_currency (ForeignKey): Foreign key to the Currency model.
    """
    objects = AppProfileManager.as_manager()
    username = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    user_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    spend_accounts = models.JSONField(default=list, null=True, blank=True)
    base_currency = models.CharField(max_length=3, default="USD")
    timezone = models.CharField(default='America/New_York')
    start_of_week = models.IntegerField(default=1)
    completed_tours = models.JSONField(default=list, null=True, blank=True)
    

    def __str__(self):
        return f"{self.user_id}"


class Tag(models.Model):
    """
    Model for tags. Allows users to add custom tags to transactions.
    Tags are automatically generated when a transaction is created if a tag is assigned and not found.
    
    Attributes:
        name (CharField): Name of the tag. Unique per user.
        uid (ForeignKey): Foreign key to the AppProfile model.
    """

    tags = models.JSONField(default=list, null=True, blank=True)
    uid = models.CharField(max_length=200, db_index=True)
    objects = TagManager.as_manager()
    def __str__(self):
        return self.tags


class PaymentSource(models.Model):
    """
    Model for payment sources. Allows users to add payment sources to their accounts.
    Automatically generates a CurrentAsset when a PaymentSource is created.

    Attributes:
        source (CharField): Name of the payment source. unique per user.
        acc_type (CharField): Type of the payment source, selected from a list of choices.
        uid (ForeignKey): Foreign key to the AppProfile model.
    """
    objects = PaymentSourceManager.as_manager()
    class Meta:
        verbose_name_plural = "Payment Sources"
        constraints = [
            models.UniqueConstraint(fields=['source', 'uid'], name='unique_source_per_user')
        ]

    class AccType(models.TextChoices):
        SAVINGS = "SAVINGS", "Savings"
        CHECKING = "CHECKING", "Checking"
        CASH = "CASH", "Cash"
        INVESTMENT = "INVESTMENT", "Investment"
        EWALLET = "EWALLET", "Mobile Wallet"
        UNKNOWN = "UNKNOWN", "Unknown"

    source = models.CharField(max_length=50)
    acc_type = models.CharField(max_length=10, choices=AccType.choices, default=AccType.UNKNOWN)
    currency = models.CharField(max_length=3, default="USD")
    amount = models.DecimalField(max_digits=15, decimal_places=2, default=0)


    # User dependancy
    uid = models.CharField(max_length=200, db_index=True)

    def __str__(self):
        return f"{self.source} ({self.AccType})"


class UpcomingExpense(models.Model):
    """
    Model for upcoming expenses. Allows users to add planned expenses to their accounts.
    Used for calculation recurring expenses, one time major planned purchases, or short-term recurring expenses.
    Turns off recurring if the end_date is reached.

    Attributes:
        name (CharField): Name of the expense.
        amount (DecimalField): Estimated cost of the expense.
        due_date (DateField): Date the expense is due.
        start_date (DateField): Date the expense starts.
        end_date (DateField): Date the expense ends.
        paid_flag (BooleanField): Flag indicating if the expense has been paid.
        expense_id (AutoField): Unique identifier for the expense.
        is_recurring (BooleanField): Flag indicating if the expense is recurring.
        currency (ForeignKey): Foreign key to the Currency model.
        uid (ForeignKey): Foreign key to the AppProfile model.
    """
    objects = UpcomingExpenseManager.as_manager()

    class Meta:
        ordering = ["due_date"]
        constraints = [
            models.UniqueConstraint(fields=['name', 'uid'], name='unique_upcoming_expense_per_user')
        ]


    name = models.CharField(max_length=200)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    due_date = models.DateField(null=True, blank=True)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    paid_flag = models.BooleanField(default=False)
    currency = models.CharField(max_length=3, default="USD")

    # User dependancy
    uid = models.CharField(max_length=200, db_index=True)

    # Boolean for recurring logic
    is_recurring = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.name} ({self.status}) ({self.paid_flag})"


class Category(models.Model):
    """
    Model for categories. Allows users to add custom categories to transactions.
    """

    class Meta:
        verbose_name_plural = "Categories",
        constraints = [
            models.UniqueConstraint(fields=['name', 'uid'], name='unique_category_per_user')
        ]

    name = models.CharField(max_length=200)
    uid = models.CharField(max_length=200, db_index=True)
    objects = CategoryManager.as_manager()
    def __str__(self):
        return self.name


class Transaction(models.Model):
    """
    Model for transactions. Allows users to add transactions to their accounts.
    Links to signals to automically update due date and paid flag for linked bill, if linked.

    Attributes:
        date (DateField): Date of the transaction.
        description (CharField): Description of the transaction.
        amount (DecimalField): Amount of the transaction.
        source (ForeignKey): Foreign key to the PaymentSource model.
        currency (ForeignKey): Foreign key to the Currency model.
        tags (ManyToManyField): Many-to-many relationship with the Tag model.
        entry_id (AutoField): Unique identifier for the transaction.
        tx_id (CharField): Unique identifier for the transaction.
        bill (ForeignKey): Foreign key to the UpcomingExpense model.
        uid (ForeignKey): Foreign key to the AppProfile model.
        tx_type (CharField): Type of the transaction, selected from a list of choices.
    """
    objects = TransactionManager.as_manager()

    class Meta:
        ordering = ["date"]
        constraints = [
            models.UniqueConstraint(fields=['tx_id', 'uid'], name='unique_transaction_per_user')
        ]
    # Hard Coded Requirements
    date = models.DateField()
    description = models.CharField(max_length=200, null=True, blank=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    created_on = models.DateField()
    category = models.CharField(max_length=200, null=True, blank=True)
    # Link to relationship models
    source = models.CharField(max_length=50)
    currency = models.CharField(max_length=3)
    tags = models.JSONField(null=True, blank=True, default=list)
    tx_id = models.CharField(max_length=20, editable=False, db_index=True)
    bill = models.CharField(max_length=200, null=True, blank=True)

    # User dependancy
    uid = models.CharField(max_length=200, db_index=True)

    class TxType(models.TextChoices):
        EXPENSE = (
            "EXPENSE",
            "Expense",
        )
        INCOME = (
            "INCOME",
            "Income",
        )
        TRANSFER_IN = (
            "XFER_IN",
            "Transfer In",
        )
        TRANSFER_OUT = (
            "XFER_OUT",
            "Transfer Out",
        )

    tx_type = models.CharField(max_length=10, choices=TxType.choices)


    def __str__(self):
        return self.tx_id


class FinancialSnapshot(models.Model):
    """
    Model for financial snapshots. Allows users to view their financial data.

    Attributes:
        total_assets (DecimalField): Total assets.
        safe_to_spend (DecimalField): Total safe to spend.
        total_savings (DecimalField): Total savings.
        total_checking (DecimalField): Total checking.
        total_investment (DecimalField): Total investment.
        total_cash (DecimalField): Total cash.
        total_ewallet (DecimalField): Total mobile wallet.
        total_monthly_spending (DecimalField): Total monthly spending.
        total_remaining_expenses (DecimalField): Total remaining expenses.
        total_leaks (DecimalField): Total leaks.
        uid (OneToOneField): One-to-one relationship with the AppProfile model.
    """
    objects = FinancialSnapshotManager.as_manager()
    class Meta:
        verbose_name_plural = "Financial Snapshot"

    total_assets = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    safe_to_spend = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    total_savings = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    total_checking = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    total_investment = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    total_cash = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    total_ewallet = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    total_monthly_spending = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    total_remaining_expenses = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    total_leaks = models.DecimalField(max_digits=15, decimal_places=2, default=0)  
    uid = models.CharField(max_length=200, db_index=True)

    def __str__(self):
        return f"{self.total_assets}, {self.safe_to_spend}, {self.total_savings}, {self.total_checking}, {self.total_investment}, {self.total_cash}, {self.total_ewallet}, {self.total_monthly_spending}, {self.total_remaining_expenses}, {self.total_leaks}"


class IdempotencyRecord(models.Model):
    """
    Stores successful mutating API responses for PWA outbox replay (D2 contract).
    Scoped by AppProfile uid (string user_id) and Idempotency-Key hash.
    """

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["uid", "key_hash"], name="idempotency_uid_key_hash_uniq"),
        ]
        indexes = [
            models.Index(fields=["created_at"]),
        ]

    uid = models.CharField(max_length=200, db_index=True)
    key_hash = models.CharField(max_length=64, db_index=True)
    method = models.CharField(max_length=8)
    path = models.CharField(max_length=512)
    status_code = models.PositiveSmallIntegerField()
    response_body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


class SupportTicket(models.Model):
    """
    Model for support tickets, including bug reports and feature requests.
    """
    class ReportType(models.TextChoices):
        BUG = "BUG", "Bug"
        FEATURE = "FEATURE", "Feature Request"

    class Severity(models.TextChoices):
        LOW = "LOW", "Low"
        MEDIUM = "MEDIUM", "Medium"
        HIGH = "HIGH", "High"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    uid = models.CharField(db_index=True, max_length=200)
    report_type = models.CharField(max_length=10, choices=ReportType.choices)
    severity = models.CharField(max_length=10, choices=Severity.choices, blank=True, null=True)
    nature = models.CharField(max_length=255)
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    diagnostic_log_key = models.CharField(max_length=255, blank=True, null=True)
    emailed = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.report_type} - {self.nature[:30]}"


class DailyUsageSnapshot(models.Model):
    """Operator-only daily usage rollup (F-014)."""

    date = models.DateField(unique=True)
    dau_count = models.PositiveIntegerField(default=0)
    mau_count = models.PositiveIntegerField(default=0)
    active_accounts = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-date"]

    def __str__(self):
        return f"usage:{self.date} dau={self.dau_count}"


class InviteChainEvent(models.Model):
    """Invite chain edge for growth analytics (F-014). Populated when invite flow ships."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    inviter_uuid = models.UUIDField(db_index=True)
    invitee_uuid = models.UUIDField(db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        indexes = [
            models.Index(fields=["created_at"]),
        ]

    def __str__(self):
        return f"invite:{self.inviter_uuid}->{self.invitee_uuid}"


class OperatorAlertState(models.Model):
    """Dedupes operator threshold alerts (24h window per alert_key)."""

    alert_key = models.CharField(max_length=64, unique=True)
    last_sent_at = models.DateTimeField()

    def __str__(self):
        return self.alert_key

 