"""
Django settings for finance_manager_api project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from finance.management.logging_config import logging_config
from dotenv import load_dotenv


def _env_bool(name: str, default: bool = False) -> bool:
    v = os.getenv(name)
    if v is None:
        return default
    return str(v).strip().lower() in ("1", "true", "yes", "on")



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv()

# Supported currencies: single source of truth from finance/data/exchange_rates.zip.
# All validation (SUPPORTED_CURRENCIES) and conversion (CURRENCY_CONVERTER) use this file.
# Production should have this file present; when missing, SUPPORTED_CURRENCIES is empty and
# conversion will fail until the file is available (e.g. via update_conversion_file command).
EXCHANGE_RATES_PATH = BASE_DIR / "finance" / "data" / "exchange_rates.zip"

if EXCHANGE_RATES_PATH.exists():
    from currency_converter import CurrencyConverter
    _converter = CurrencyConverter(
        str(EXCHANGE_RATES_PATH),
        decimal=True,
        fallback_on_wrong_date=True,
        fallback_on_missing_rate=True,
    )
    SUPPORTED_CURRENCIES = list(_converter.currencies)
    CURRENCY_CONVERTER = _converter
else:
    SUPPORTED_CURRENCIES = []
    CURRENCY_CONVERTER = None

# Set up logging configuration
logging_config()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DEBUG", default=False)
DB_HIT_LOGGING_ENABLED = DEBUG
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@financemanager.local")
BUG_REPORT_TO_EMAIL = os.getenv("BUG_REPORT_TO_EMAIL", "")
SUPPORT_DIGEST_TO_EMAIL = os.getenv("SUPPORT_DIGEST_TO_EMAIL", BUG_REPORT_TO_EMAIL)
OPERATOR_NOTIFY_EMAIL = os.getenv("OPERATOR_NOTIFY_EMAIL", BUG_REPORT_TO_EMAIL)
BETA_FEATURE_REQUESTS_ENABLED = _env_bool("BETA_FEATURE_REQUESTS_ENABLED", default=False)

# Email (Proton Bridge SMTP on VPS — see deploy/server.env.example)
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = _env_bool("EMAIL_USE_TLS", default=True)
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")

# F-014 DAU threshold alerts (comma-separated integers)
DAU_ALERT_THRESHOLDS = os.getenv("DAU_ALERT_THRESHOLDS", "10,50,100")

# When False (default), request logs use uid + a non-identifying username label.
# Set LOG_FULL_USERNAME=1 only for local debugging of auth-related issues.
LOG_FULL_USERNAME = _env_bool("LOG_FULL_USERNAME", default=False)

ALLOWED_HOSTS = [
    h.strip()
    for h in os.getenv("ALLOWED_HOSTS", default="localhost,127.0.0.1").split(",")
    if h.strip()
]


# CSRF and CORS (simplified for local HTTPS simulation)
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CSRF_TRUSTED_ORIGINS",
        "https://financemanager.local:8443,https://api.financemanager.local:8443,"
        "https://thehivemanager.com,https://www.thehivemanager.com,"
        "https://api.thehivemanager.com,https://api-jsdevtesting.thehivemanager.com,"
        "https://jsdevtesting.thehivemanager.com",
    ).split(",")
    if origin.strip()
]
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CORS_ALLOWED_ORIGINS",
        "http://localhost:4173,http://127.0.0.1:4173,"
        "http://localhost:5173,http://127.0.0.1:5173,"
        "https://thehivemanager.com,https://jsdevtesting.thehivemanager.com,"
        "https://api-jsdevtesting.thehivemanager.com",
    ).split(",")
    if origin.strip()
]
CORS_ALLOW_CREDENTIALS = True

# Extend default CORS headers to include custom PWA/D2 headers the SPA sends
# on mutating requests (X-Client-Build for forced upgrade, Idempotency-Key
# for offline outbox replay). Without these the browser preflight blocks all
# cross-origin POST/PATCH/DELETE.
from corsheaders.defaults import default_headers

CORS_ALLOW_HEADERS = (
    *default_headers,
    "x-client-build",
    "idempotency-key",
)


# Application definition

INSTALLED_APPS = [
    # Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # My apps
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "finance",
    "drf_spectacular",

    # Auth & Social Login
    "django.contrib.sites",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.github",
    "corsheaders",
    "axes",
]

SITE_ID = 1

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

from datetime import timedelta

# JWT lifetimes (djangorestframework-simplejwt). Access token lasts 1 day; 
# Refresh token lasts 7 days and allows obtaining new access tokens without relogin.
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_COOKIE": "finance-auth",
    "JWT_AUTH_REFRESH_COOKIE": "finance-refresh-token",
    "TOKEN_MODEL": None,
    "REGISTER_SERIALIZER": (
        "finance.api_tools.serializers.register_serializers.EmailUniqueRegisterSerializer"
    ),
}

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# CorsMiddleware first so preflight/Origin handling runs before the rest of the stack
# (django-cors-headers recommends placing it as high as possible).
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "finance.middleware.db_hit_counter.DBHitCounterMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "finance.middleware.user_log_context.UserLogContextMiddleware",
    "finance.middleware.pwa_write_contract.PwaWriteContractMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "axes.middleware.AxesMiddleware",
]

ROOT_URLCONF = "finance_api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "finance_api.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Default: local SQLite.
# If Postgres env vars are provided, use PostgreSQL automatically.
_db_engine = os.getenv("DB_ENGINE", "").strip()
_db_name = os.getenv("DB_NAME", "").strip()
_db_user = os.getenv("DB_USER", "").strip()
_db_password = os.getenv("DB_PASSWORD", "").strip()
_db_host = os.getenv("DB_HOST", "127.0.0.1").strip()
_db_port = os.getenv("DB_PORT", "5432").strip()

_use_postgres = (
    _db_engine in {"django.db.backends.postgresql", "postgres", "postgresql"}
    and _db_name
    and _db_user
    and _db_password
)

if _use_postgres:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": _db_name,
            "USER": _db_user,
            "PASSWORD": _db_password,
            "HOST": _db_host,
            "PORT": _db_port,
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 12,
        }
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
    {
        "NAME": "finance.validators.password_complexity.ComplexPasswordValidator",
    },
]

# Password Hashers (Argon2 as default)
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

# Django-Axes (rate limiting / lockouts behind nginx proxy)
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # hours
AXES_RESET_ON_SUCCESS = True
AXES_LOCKOUT_PARAMETERS = ["username", "ip_address"]
AXES_IPWARE_PROXY_COUNT = int(os.getenv("AXES_IPWARE_PROXY_COUNT", "1") or "1")
AXES_IPWARE_META_PRECEDENCE_ORDER = (
    "HTTP_X_FORWARDED_FOR",
    "REMOTE_ADDR",
)


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# drf-spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Finance Manager API',
    'DESCRIPTION': 'Financial data management API with zero-knowledge aspirations.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'],
    'COMPONENT_SPLIT_PATCH': True,
    'COMPONENT_SPLIT_REQUEST': True,
}

# PWA / D2: optional write compatibility window (null = off). Semver-like strings
# (e.g. 1.2.0) compare segment-wise; otherwise lexicographic string compare.
CLIENT_BUILD_MIN_WRITE = os.getenv("CLIENT_BUILD_MIN_WRITE", "").strip() or None
API_SERVER_BUILD = os.getenv("API_SERVER_BUILD", "").strip() or "dev"
CLIENT_UPGRADE_DOCUMENTATION_URL = os.getenv(
    "CLIENT_UPGRADE_DOCUMENTATION_URL",
    "https://thehivemanager.com",
).strip()

# Idempotency-Key retention for replay cache (days).
IDEMPOTENCY_RETENTION_DAYS = int(os.getenv("IDEMPOTENCY_RETENTION_DAYS", "7") or "7")

# HTTPS and cookie security (set explicitly in production / beta; deploy check uses these
# when DEBUG is False and documents intentional proxy termination where applicable)
SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", default=False)
SESSION_COOKIE_SECURE = _env_bool("SESSION_COOKIE_SECURE", default=False)
CSRF_COOKIE_SECURE = _env_bool("CSRF_COOKIE_SECURE", default=False)
_hsts = os.getenv("SECURE_HSTS_SECONDS", "").strip()
if _hsts.isdigit():
    SECURE_HSTS_SECONDS = int(_hsts)
elif SECURE_SSL_REDIRECT:
    SECURE_HSTS_SECONDS = 31536000
else:
    SECURE_HSTS_SECONDS = 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool(
    "SECURE_HSTS_INCLUDE_SUBDOMAINS",
    default=SECURE_HSTS_SECONDS > 0,
)
SECURE_HSTS_PRELOAD = _env_bool(
    "SECURE_HSTS_PRELOAD",
    default=SECURE_HSTS_SECONDS > 0,
)

# Strict HTTP headers
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

# Celery Configuration Options
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", os.environ.get("REDIS_URL", "redis://localhost:6379/0"))
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", os.environ.get("REDIS_URL", "redis://localhost:6379/0"))
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    "send-weekly-support-digest": {
        "task": "finance.tasks.support_digest.send_weekly_feature_requests_email",
        "schedule": crontab(hour=9, minute=0, day_of_week="monday"),
    },
    "rollup-daily-usage": {
        "task": "finance.tasks.usage_rollup.rollup_daily_usage",
        "schedule": crontab(hour=0, minute=5),
    },
}
