"""
Django settings for finance_manager_api project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from finance.management.logging_config import logging_config
from dotenv import load_dotenv


def _env_bool(name: str, default: bool = False) -> bool:
    v = os.getenv(name)
    if v is None:
        return default
    return str(v).strip().lower() in ("1", "true", "yes", "on")



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv()

# Supported currencies: single source of truth from finance/data/exchange_rates.zip.
# All validation (SUPPORTED_CURRENCIES) and conversion (CURRENCY_CONVERTER) use this file.
# Production should have this file present; when missing, SUPPORTED_CURRENCIES is empty and
# conversion will fail until the file is available (e.g. via update_conversion_file command).
EXCHANGE_RATES_PATH = BASE_DIR / "finance" / "data" / "exchange_rates.zip"

if EXCHANGE_RATES_PATH.exists():
    from currency_converter import CurrencyConverter
    _converter = CurrencyConverter(
        str(EXCHANGE_RATES_PATH),
        decimal=True,
        fallback_on_wrong_date=True,
        fallback_on_missing_rate=True,
    )
    SUPPORTED_CURRENCIES = list(_converter.currencies)
    CURRENCY_CONVERTER = _converter
else:
    SUPPORTED_CURRENCIES = []
    CURRENCY_CONVERTER = None

# Set up logging configuration
logging_config()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DEBUG", default=False)
DB_HIT_LOGGING_ENABLED = DEBUG
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@financemanager.local")
BUG_REPORT_TO_EMAIL = os.getenv("BUG_REPORT_TO_EMAIL", "")

# When False (default), request logs use uid + a non-identifying username label.
# Set LOG_FULL_USERNAME=1 only for local debugging of auth-related issues.
LOG_FULL_USERNAME = _env_bool("LOG_FULL_USERNAME", default=False)

ALLOWED_HOSTS = [
    h.strip()
    for h in os.getenv("ALLOWED_HOSTS", default="localhost,127.0.0.1").split(",")
    if h.strip()
]


# CSRF and CORS (simplified for local HTTPS simulation)
CSRF_TRUSTED_ORIGINS = [
    "https://financemanager.local:8443",
    "https://api.financemanager.local:8443",
]


# Application definition

INSTALLED_APPS = [
    # Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # My apps
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "finance",
    "drf_spectacular",

    # Auth & Social Login
    "django.contrib.sites",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.github",
]

SITE_ID = 1

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

from datetime import timedelta

# JWT lifetimes (djangorestframework-simplejwt). Access token lasts 1 day; 
# Refresh token lasts 7 days and allows obtaining new access tokens without relogin.
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_COOKIE": "finance-auth",
    "JWT_AUTH_REFRESH_COOKIE": "finance-refresh-token",
    "TOKEN_MODEL": None,
}

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

MIDDLEWARE = [
    "finance.middleware.db_hit_counter.DBHitCounterMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "finance.middleware.user_log_context.UserLogContextMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "finance_api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "finance_api.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Default: local SQLite.
# If Postgres env vars are provided, use PostgreSQL automatically.
_db_engine = os.getenv("DB_ENGINE", "").strip()
_db_name = os.getenv("DB_NAME", "").strip()
_db_user = os.getenv("DB_USER", "").strip()
_db_password = os.getenv("DB_PASSWORD", "").strip()
_db_host = os.getenv("DB_HOST", "127.0.0.1").strip()
_db_port = os.getenv("DB_PORT", "5432").strip()

_use_postgres = (
    _db_engine in {"django.db.backends.postgresql", "postgres", "postgresql"}
    and _db_name
    and _db_user
    and _db_password
)

if _use_postgres:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": _db_name,
            "USER": _db_user,
            "PASSWORD": _db_password,
            "HOST": _db_host,
            "PORT": _db_port,
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# drf-spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Finance Manager API',
    'DESCRIPTION': 'Financial data management API with zero-knowledge aspirations.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'],
    'COMPONENT_SPLIT_PATCH': True,
    'COMPONENT_SPLIT_REQUEST': True,
}

# HTTPS and cookie security (set explicitly in production / beta; deploy check uses these
# when DEBUG is False and documents intentional proxy termination where applicable)
SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", default=False)
SESSION_COOKIE_SECURE = _env_bool("SESSION_COOKIE_SECURE", default=False)
CSRF_COOKIE_SECURE = _env_bool("CSRF_COOKIE_SECURE", default=False)
_hsts = os.getenv("SECURE_HSTS_SECONDS", "").strip()
SECURE_HSTS_SECONDS = int(_hsts) if _hsts.isdigit() else 0
